import { useEffect, useMemo, useState } from 'react'
import { deleteLocalAuthUser, getIdToken, observeAuth, signIn, signOut, type AuthProviderName, type User } from '@bike-tools/auth'
import { compareSessions, summarizeSide, type TensionMeasurement, type TensionSession, type Wheel, type WheelSide } from '@bike-tools/bike-core'
import { apiRequest } from '@bike-tools/db'

type Draft = Record<WheelSide, string[]>
const emptyDraft = (count: number): Draft => ({ left: Array(Math.ceil(count / 2)).fill(''), right: Array(Math.floor(count / 2)).fill('') })
const n = (value: string) => value.trim() ? Number(value) : null
const fmt = (value: number | null, suffix = '') => value === null ? '—' : `${value.toFixed(1)}${suffix}`

function SignIn() {
  const [busy, setBusy] = useState<AuthProviderName | null>(null); const [error, setError] = useState('')
  const connect = async (provider: AuthProviderName) => { try { setBusy(provider); setError(''); await signIn(provider) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Sign-in failed') } finally { setBusy(null) } }
  return <main className="signin"><div className="signin-copy"><div className="brand"><span>SB</span> SPOKE BENCH</div><p className="eyebrow">PRECISION WHEEL WORKSHOP</p><h1>Every spoke.<br/><em>In balance.</em></h1><p>Measure tension, spot inconsistencies, and track your wheels over time.</p></div><section className="signin-card"><div className="wheel-logo">◎</div><h2>Welcome to your workbench</h2><p>Sign in to save wheels and tension sessions.</p>{(['google','apple','facebook'] as const).map(provider => <button key={provider} disabled={!!busy} onClick={() => connect(provider)}>Continue with {provider[0]?.toUpperCase()}{provider.slice(1)}</button>)}{error && <p className="error" role="alert">{error}</p>}<small>We store only your Firebase user ID with workshop data.</small></section></main>
}

function WheelForm({ onSave, onCancel }: { onSave: (wheel: Omit<Wheel, 'id'|'createdAt'|'updatedAt'|'tensionUnit'>) => Promise<void>; onCancel?: () => void }) {
  const [form, setForm] = useState({ name: '', position: 'rear' as const, spokeCount: '28', rim: '', hub: '', targetLeft: '75', targetRight: '120' }); const [busy, setBusy] = useState(false)
  const field = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement|HTMLSelectElement>) => setForm({ ...form, [key]: event.target.value })
  return <form className="card form" onSubmit={async event => { event.preventDefault(); setBusy(true); try { await onSave({ name: form.name || null, position: form.position, spokeCount: Number(form.spokeCount), rim: form.rim || null, hub: form.hub || null, targetLeft: n(form.targetLeft), targetRight: n(form.targetRight) }) } finally { setBusy(false) } }}><div className="card-head"><div><p className="eyebrow">NEW PROFILE</p><h2>Add a wheel</h2></div>{onCancel && <button className="icon-button" type="button" onClick={onCancel}>×</button>}</div><div className="form-grid"><label>Wheel name<input required maxLength={100} value={form.name} onChange={field('name')} placeholder="Trail bike rear" /></label><label>Position<select value={form.position} onChange={field('position')}><option value="front">Front</option><option value="rear">Rear</option></select></label><label>Spoke count<select value={form.spokeCount} onChange={field('spokeCount')}>{[24,28,32,36].map(x => <option key={x}>{x}</option>)}</select></label><label>Rim<input value={form.rim} onChange={field('rim')} placeholder="DT Swiss EX 511" /></label><label>Hub<input value={form.hub} onChange={field('hub')} placeholder="DT Swiss 350" /></label><label>Left target (kgf)<input type="number" min="1" max="500" value={form.targetLeft} onChange={field('targetLeft')} /></label><label>Right target (kgf)<input type="number" min="1" max="500" value={form.targetRight} onChange={field('targetRight')} /></label></div><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Create wheel'}</button></form>
}

function WheelDiagram({ draft, selected, onSelect, stats }: { draft: Draft; selected: [WheelSide,number]; onSelect: React.Dispatch<React.SetStateAction<[WheelSide,number]>>; stats: Record<WheelSide, ReturnType<typeof summarizeSide>> }) {
  const entries = (['left','right'] as const).flatMap(side => draft[side].map((value,index) => ({ side,index,value:n(value) }))); const cx=150, cy=150, rim=119
  return <div className="diagram"><svg viewBox="0 0 300 300" aria-label="Interactive wheel spoke diagram"><circle className="rim" cx={cx} cy={cy} r={rim}/><circle className="hub" cx={cx} cy={cy} r="23"/>{entries.map(({side,index,value},globalIndex) => { const a=(globalIndex/entries.length)*Math.PI*2-Math.PI/2; const x=cx+Math.cos(a)*rim; const y=cy+Math.sin(a)*rim; const average=stats[side].average; const bad=value!==null && average!==null && Math.abs(value-average)/average>.1; return <g key={`${side}${index}`} className={`spoke ${side} ${bad?'bad':''} ${selected[0]===side&&selected[1]===index?'selected':''}`} role="button" tabIndex={0} onClick={()=>onSelect([side,index])} onKeyDown={e=>{if(e.key==='Enter')onSelect([side,index])}}><line x1={cx} y1={cy} x2={x} y2={y}/><circle cx={x} cy={y} r="8"/><text x={x} y={y+3}>{index+1}</text></g>})}<circle className="axle" cx={cx} cy={cy} r="5"/></svg><p>Click a spoke to enter its tension</p></div>
}

function SessionEditor({ wheel, history, onSaved }: { wheel: Wheel; history: TensionSession[]; onSaved: () => Promise<void> }) {
  const [draft,setDraft]=useState(()=>emptyDraft(wheel.spokeCount)); const [selected,setSelected]=useState<[WheelSide,number]>(['left',0]); const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
  useEffect(()=>setDraft(emptyDraft(wheel.spokeCount)),[wheel.id,wheel.spokeCount])
  const measurements=useMemo(()=> (['left','right'] as const).flatMap(side=>draft[side].flatMap((value,index)=>n(value) ? [{spokeNumber:index*2+(side==='left'?1:2),side,positionIndex:index,tension:Number(value)}] : [])),[draft])
  const stats={left:summarizeSide(measurements,'left',wheel.targetLeft),right:summarizeSide(measurements,'right',wheel.targetRight)}
  const comparison=history[0] ? compareSessions(measurements,history[0].measurements) : []
  const update=(side:WheelSide,index:number,value:string)=>setDraft(current=>({...current,[side]:current[side].map((v,i)=>i===index?value:v)}))
  const save=async()=>{if(!measurements.length)return;setBusy(true);setMessage('');try{const token=await getIdToken();await apiRequest('tension-session',token,{method:'POST',body:JSON.stringify({wheelId:wheel.id,notes:notes||null,measurements})});setDraft(emptyDraft(wheel.spokeCount));setNotes('');setMessage('Session saved');await onSaved()}catch(e){setMessage(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}
  return <section className="workspace"><div className="section-title"><div><p className="eyebrow">LIVE SESSION</p><h2>{wheel.name || `${wheel.position} wheel`}</h2></div><div className="session-progress"><strong>{measurements.length}/{wheel.spokeCount}</strong><span>spokes measured</span></div></div><div className="analysis-grid"><div className="card chart-card"><WheelDiagram draft={draft} selected={selected} onSelect={setSelected} stats={stats}/></div><div className="card entry-card"><p className="eyebrow">SELECTED SPOKE</p><h3>{selected[0] === 'left' ? 'Left' : 'Right'} · {selected[1]+1}</h3><label>Tension (kgf)<input autoFocus type="number" min="1" max="500" value={draft[selected[0]][selected[1]]} onChange={e=>update(selected[0],selected[1],e.target.value)} /></label><div className="nudge"><button onClick={()=>update(selected[0],selected[1],String(Math.max(1,(n(draft[selected[0]][selected[1]])||1)-1)))}>−1</button><button onClick={()=>update(selected[0],selected[1],String((n(draft[selected[0]][selected[1]])||0)+1))}>+1</button></div><p>Target: {selected[0]==='left'?wheel.targetLeft:wheel.targetRight} kgf</p></div></div><div className="stats">{(['left','right'] as const).map(side=><article className="card" key={side}><p className="eyebrow">{side.toUpperCase()} SIDE</p><strong>{fmt(stats[side].average)}</strong><span>kgf average</span><dl><div><dt>Minimum</dt><dd>{fmt(stats[side].minimum)}</dd></div><div><dt>Maximum</dt><dd>{fmt(stats[side].maximum)}</dd></div><div><dt>Std. deviation</dt><dd>{fmt(stats[side].standardDeviation)}</dd></div><div><dt>From target</dt><dd>{fmt(stats[side].targetDeviationPercent,'%')}</dd></div></dl></article>)}</div><div className="card session-save"><label>Session notes<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Trued wheel; checked after first ride…"/></label><div><small>{history[0] && comparison.length ? `Compared with last session: ${comparison.filter(x=>Math.abs(x.change)>=5).length} spokes changed ≥5 kgf.` : 'Your first saved session becomes the comparison baseline.'}</small><button className="primary" disabled={busy||!measurements.length} onClick={save}>{busy?'Saving…':'Save session'}</button></div>{message&&<p className="notice" role="status">{message}</p>}</div></section>
}

function App() {
  const [user,setUser]=useState<User|null|undefined>(undefined); const [wheels,setWheels]=useState<Wheel[]>([]); const [active,setActive]=useState<string>(''); const [history,setHistory]=useState<TensionSession[]>([]); const [adding,setAdding]=useState(false); const [error,setError]=useState('')
  useEffect(()=>observeAuth(setUser),[])
  const load=async()=>{if(!user)return;try{const token=await getIdToken();const data=await apiRequest<Wheel[]>('wheels',token);if(!Array.isArray(data))throw new Error('The wheels API returned an invalid response');setWheels(data);setActive(current=>current||data[0]?.id||'')}catch(e){setWheels([]);setError(e instanceof Error?e.message:'Could not load wheels')}}
  useEffect(()=>{void load()},[user])
  const current=wheels.find(w=>w.id===active)
  const loadHistory=async()=>{if(!current)return;const token=await getIdToken();const rows=await apiRequest<Array<Record<string,unknown>>>('tension-history?wheelId='+current.id,token);setHistory(rows.map(row=>({id:String(row.id),wheelId:String(row.wheel_id),notes:row.notes as string|null,createdAt:String(row.created_at),measurements:(row.spoke_measurements as Array<Record<string,unknown>>).map(m=>({id:String(m.id),spokeNumber:Number(m.spoke_number),side:m.side as WheelSide,positionIndex:Number(m.position_index),tension:Number(m.tension)}))})))}
  useEffect(()=>{void loadHistory().catch(e=>setError(e.message))},[current?.id])
  if(user===undefined)return <div className="loading">Loading workbench…</div>
  if(!user)return <SignIn/>
  const create=async(wheel:Omit<Wheel,'id'|'createdAt'|'updatedAt'|'tensionUnit'>)=>{const token=await getIdToken();const created=await apiRequest<Wheel>('wheels',token,{method:'POST',body:JSON.stringify(wheel)});setWheels([created,...wheels]);setActive(created.id);setAdding(false)}
  const exportData=async()=>{const token=await getIdToken();const data=await apiRequest('export-data',token);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='spoke-bench-export.json';a.click();URL.revokeObjectURL(url)}
  const removeAccount=async()=>{if(!confirm('Permanently delete all wheel data and your account? This cannot be undone.'))return;try{const token=await getIdToken(true);await apiRequest('account',token,{method:'DELETE'});await deleteLocalAuthUser()}catch(e){setError(e instanceof Error?e.message:'Deletion failed. Sign in again and retry.')}}
  return <div className="app"><header><div className="brand"><span>SB</span> SPOKE BENCH</div><nav><button onClick={()=>setAdding(true)}>+ Add wheel</button><button onClick={exportData}>Export data</button><button onClick={()=>signOut()}>Sign out</button></nav></header><div className="layout"><aside><p className="eyebrow">MY WHEELS</p>{wheels.map(w=><button key={w.id} className={active===w.id?'active':''} onClick={()=>setActive(w.id)}><span className="mini-wheel">◎</span><span><strong>{w.name||'Untitled wheel'}</strong><small>{w.position} · {w.spokeCount} spokes</small></span></button>)}<div className="account"><button onClick={removeAccount}>Delete account</button><small>Deletes all saved data and Firebase identity.</small></div></aside><main><div className="page-head"><div><p className="eyebrow">WHEEL WORKSHOP / TENSION</p><h1>Tension manager</h1></div>{current&&<div className="wheel-meta"><span>{current.rim||'No rim'}</span><span>{current.hub||'No hub'}</span><span>{current.spokeCount} spokes</span></div>}</div>{error&&<p className="error" role="alert">{error}</p>}{adding||!wheels.length?<WheelForm onSave={create} onCancel={wheels.length?()=>setAdding(false):undefined}/>:current&&<><SessionEditor wheel={current} history={history} onSaved={loadHistory}/><section className="history"><div className="section-title"><div><p className="eyebrow">SERVICE RECORD</p><h2>Session history</h2></div></div>{history.length?<div className="history-list">{history.map(item=><article className="card" key={item.id}><div><strong>{new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.createdAt))}</strong><p>{item.notes||'No notes'}</p></div><span>{item.measurements.length} readings</span></article>)}</div>:<div className="empty">No saved sessions yet. Complete a measurement above to begin your wheel history.</div>}</section></>}</main></div></div>
}
export default App
